### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by NuggetFangus** [qingjun1991/GameDreamFactory#10]
Chars with storyboard result in black screen, this didnt happen before

**Comment by qingjun1991** [comment]
The problem has been resolved, please update the patch!

**Comment by NuggetFangus** [comment]
Thank you!

**Comment by NuggetFangus** [comment]
When you have a char that has color select or groove select, if you press one button to select the color/groove it starts the fight instead

**Comment by qingjun1991** [comment]
Send me your character pack to take a look.

**Comment by NuggetFangus** [comment]
https://onedrive.live.com/?id=FE71D6C299938D39%21141&cid=FE71D6C299938D39&authkey=%21AE1IxTFDt2cRqGw

Its the Donald_Infinite_SE

**Comment by NuggetFangus** [comment]
But the issue happens with every char that has an option before the fight

**Comment by qingjun1991** [comment]
> https://onedrive.live.com/?id=FE71D6C299938D39%21141&cid=FE71D6C299938D39&authkey=%21AE1IxTFDt2cRqGw
> 
> Its the Donald_Infinite_SE

I am unable to access this download link in my country.

**Comment by NuggetFangus** [comment]
https://mugenarchive.com/forums/downloads.php?do=file&id=57920-donald-infinite-sennou-room

**Comment by qingjun1991** [comment]
I have tried it and did not encounter the problem you mentioned. The result is the same as Mugen-1.1b1. Perhaps it is an issue with your screen package. You can try using the original Mugen-1.1b1.

**Comment by NuggetFangus** [comment]
I used 2 screenpacks and both have the same issue, plus im on the mobile version

**Comment by qingjun1991** [comment]
Perhaps you have some operational details, could you record the screen for me to see?

**Comment by NuggetFangus** [comment]
https://github.com/qingjun1991/GameDreamFactory/assets/81289862/7233009e-f909-45f0-bc97-1bfae66038c8

**Comment by NuggetFangus** [comment]
When i click on the button instead of choosing the palette and ex or normal mode, it skips to the battle

**Comment by qingjun1991** [comment]
In Mugen-1.1b1, it's also like this.

**Comment by NuggetFangus** [comment]
But even pressing enter it still skips it

**Comment by NuggetFangus** [comment]
So its not a bug?

**Comment by qingjun1991** [comment]
Yes, I guess you made a mistake with the button. You should have pressed the directional key to choosing the palette and ex or normal mode.

**Comment by qingjun1991** [comment]
Yes, I guess you made a mistake with the button. You should have pressed the directional button to choosing the palette and ex or normal mode.

**Comment by NuggetFangus** [comment]
I know, but i thought that pressing enter would confirm the action

**Comment by NuggetFangus** [comment]
But if its not a bug then thats okay

**Comment by qingjun1991** [comment]
In the video, you pressed the "a" button, which is the same as "mugen-1.1b1" to confirm and start the game.

**Comment by NuggetFangus** [comment]
Oh, sorry, i pressed the wrong button, but pressing enter still skips it

**Comment by NuggetFangus** [comment]
You know the one at the side of the pause button

**Comment by qingjun1991** [comment]
Oh, I finally understand what you mean, Is "Start“ button.

**Comment by NuggetFangus** [comment]
Sorry for the misunderstanding

**Comment by qingjun1991** [comment]
The problem has been resolved, please update the "GameDreamFactory.Core.dll"!

**Comment by NuggetFangus** [comment]
Thank you very much

**Comment by NuggetFangus** [comment]
This stage is bugged when you walk

https://mugenarchive.com/forums/downloads.php?do=file&id=114544-doom-e1-m1-mackx-compiffytune

**Comment by qingjun1991** [comment]
What's different from mugen-1.1b1? I have tried and haven't found anything different.

**Comment by NuggetFangus** [comment]
It has graphical glitches when you walk, but it should not have the glitches

**Comment by qingjun1991** [comment]
I didn't find any problems. Could you record the screen for me to see?

**Comment by NuggetFangus** [comment]
https://github.com/user-attachments/assets/6ee6d92a-7afd-4530-bab4-3e7ef8413ba8

**Comment by qingjun1991** [comment]
The problem has been resolved, please update the "GameDreamFactory.Core.dll" and "GameDreamFactory.MonoGame.Core.dll"!

**Comment by NuggetFangus** [comment]
Yooooo thank you, good job man
