### ISSUE TITLE
SD CARD 

### ISSUE THREAD

**Issue by NuggetFangus** [qingjun1991/GameDreamFactory#11]
Does game dream factory support sd card? Like so i can put my mugens in my sd card

**Comment by qingjun1991** [comment]
Supported!

**Comment by NuggetFangus** [comment]
How do i make it read the sd card?

**Comment by qingjun1991** [comment]
Currently only support older version of Android system.

**Comment by NuggetFangus** [comment]
Oh ok

**Comment by qingjun1991** [comment]
The new Android system is now supported!

**Comment by NuggetFangus** [comment]
Ayooooo thats crazy! But how can i make it support?

**Comment by qingjun1991** [comment]
update the patch, Launch the app. Select !GameDreamFactory folder, or File->Open folder.

**Comment by NuggetFangus** [comment]
Oh ok, thank you!!

**Comment by NuggetFangus** [comment]
Im getting an error saying acess denied

**Comment by qingjun1991** [comment]
Can it be used normally before?

**Comment by NuggetFangus** [comment]
I dont know, but i dont think so

**Comment by qingjun1991** [comment]
I'm not sure, please record a video for me.

**Comment by NuggetFangus** [comment]
https://github.com/user-attachments/assets/4dae316a-dc31-427a-b38c-f632993f0855

**Comment by qingjun1991** [comment]
This is normal, this feature requires directly access to files, but the new android system does not allow app to directly access certain special folders and files.

You can use File ->Open folder. Because this is accessed in a special way, it can be accessed.

**Comment by NuggetFangus** [comment]
Open folder doesnt work either for some reason, maybe because the folder is too heavy

**Comment by qingjun1991** [comment]
You can try opening a small folder first.

**Comment by NuggetFangus** [comment]
A small folder doesnt work either

**Comment by qingjun1991** [comment]
The folder must be a "!GameDreamFactory" folder, which means it must have "CQJ.Libs" folder.

**Comment by NuggetFangus** [comment]
Actually it loads after some time, the small one loads faster, the bigger one took about 3 to 5 minutes, and after some time trying to load my roster, it crashes

**Comment by qingjun1991** [comment]
Then you can only use mini games, it's a limitation of the new Android system, Only root can lift restrictions.

**Comment by NuggetFangus** [comment]
Maybe ill do root sometime then
