### ISSUE TITLE
I can't get past the special moves screen in the moves list in the MK mugen games

### ISSUE THREAD

**Issue by Lklkjddjd** [qingjun1991/GameDreamFactory#16]
When I press the buttons to go to the fatality list it doesn't detect it, is there a way to fix it?

https://github.com/qingjun1991/GameDreamFactory/assets/171199696/f94d645c-5e92-4c01-bd56-86c8ecd1c8cb

**Comment by qingjun1991** [comment]
Send me your game download link so I can see what the problem is.

**Comment by Lklkjddjd** [comment]
> Send me your game download link so I can see what the problem is.

https://www.mediafire.com/file/auun91aisjeifa4/MKP_Davex_Editon.rar/file

**Comment by Lklkjddjd** [comment]
Also when I press block + run, which is the button to reach the fatality list, the game does not detect it

**Comment by qingjun1991** [comment]
The problem has been resolved, please update the patch!

**Comment by Lklkjddjd** [comment]
Thanks you very much
