### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by NuggetFangus** [qingjun1991/GameDreamFactory#20]
Is there any way i can add survival mode again manually?

**Comment by qingjun1991** [comment]
For flexibility, the game dream factory uses the method of adding code to implement different modes.

Examples:

Survival Mode:
"!GameDreamFactory\stages\bwBase1横版.def"

Survivors Mode:
"!GameDreamFactory\stages\bwBase1横版格斗幸存者.def"

LeadSoldier Mode:
"!GameDreamFactory\stages\bwBase1横版百兵.def"

Melee Mode:
"!GameDreamFactory\stages\bwBase1横版混战.def"

Tag Mode:
"!GameDreamFactory\stages\kfm宽屏Tag.def"

Turns Mode:
"!GameDreamFactory\stages\kfm宽屏车轮战.def"

**Comment by NuggetFangus** [comment]
But what about default survival mode? That comes with mugen, can i enable it again?

**Comment by qingjun1991** [comment]
No, the fixed mode is not what I want.
