### ISSUE TITLE
how do i control player 1 & player 2 at the same time like mugen

### ISSUE THREAD

**Issue by CheeksTheOriginal** [qingjun1991/GameDreamFactory#23]
i want to know how to control both player while in training mode like what your able to do in mugen

**Comment by NuggetFangus** [comment]
I think you need to configure the player 2 inputs in the mugen.cfg

**Comment by qingjun1991** [comment]
If you are a mobile player

Solution 1: External computer keyboard
Solution 2: "!GameDreamFactory\TouchButton.def"，[Button] Input=1
Solution 3: Online

**Comment by CheeksTheOriginal** [comment]
> If you are a mobile player
> 
> Solution 1: External computer keyboard Solution 2: "!GameDreamFactory\TouchButton.def"，[Button] Input=1 Solution 3: Online

thanks so much bro, input = 1 is perfect 👌
