### ISSUE TITLE
where is the ai activation code for p1 when you press RUp

### ISSUE THREAD

**Issue by CheeksTheOriginal** [qingjun1991/GameDreamFactory#24]
where is the ai activation code for p1 when you press RUp.

**Comment by qingjun1991** [comment]
"!GameDreamFactory\SystemAI.cns"

;打开ai开关
[State ]
type = VarSet
trigger1 = command = "hold∧RUp_sys" && !(root,AILevel+AILevel)
var(59) = 1

;关闭ai开关
[State ]
type = VarSet
trigger1 = command = "hold∨RDown_sys" && !(root,AILevel+AILevel)
var(59) = 0

**Comment by CheeksTheOriginal** [comment]
thx
