### ISSUE TITLE
Tag Mode

### ISSUE THREAD

**Issue by NuggetFangus** [qingjun1991/GameDreamFactory#25]
How can i add your tag code to a character? I didnt understand very well

**Comment by qingjun1991** [comment]
The stage "!GameDreamFactory\stages\kfm宽屏Tag.def" add a character "!GameDreamFactory\chars\道具\Tag\Tag.def",
This character is responsible for controlling  all characters in and out.

**Comment by NuggetFangus** [comment]
oh ok thank you
