### ISSUE TITLE
is it possible to change the touch.def when a button is pressed

### ISSUE THREAD

**Issue by CheeksTheOriginal** [qingjun1991/GameDreamFactory#26]
can someone please write a state that changes the touch.def when specific button is pressed, i can't get it to work

**Comment by qingjun1991** [comment]
Can.

example:
"!GameDreamFactory\chars\射击\射击.def".

details:
"!GameDreamFactory\游戏梦工厂&Mugen的教程\游戏梦工厂\Sctrls(人物的State)\ChangeTouchButtonDef(改变按钮定义文件).txt"
