### ISSUE TITLE
My version of GameDreamFactory

### ISSUE THREAD

**Issue by CheeksTheOriginal** [qingjun1991/GameDreamFactory#27]
hello author i wanted you to test GameDreamFactory version that i put together for android
https://www.mediafire.com/file/berr3efrsbxcpfd/GameDreamFactory.7z/file

**Comment by qingjun1991** [comment]
This is pretty good!

**Comment by CheeksTheOriginal** [comment]
> This is pretty good!

I'm glad you like it!

**Comment by CheeksTheOriginal** [comment]
> hello author i wanted you to test GameDreamFactory version that i put together for android https://www.mediafire.com/file/berr3efrsbxcpfd/GameDreamFactory.7z/file

Update Implemented
