### ISSUE TITLE
I can't get the SelectAddPlayer code to work

### ISSUE THREAD

**Issue by CheeksTheOriginal** [qingjun1991/GameDreamFactory#29]
I can't figure out how to make the SelectAddPlayer code to work

**Comment by qingjun1991** [comment]
examples:
"!GameDreamFactory\stages\bwBase1横版格斗幸存者.def"
"!GameDreamFactory\chars\道具\格斗幸存者\格斗幸存者.def"

"!GameDreamFactory\stages\bwBase1横版百兵.def"
"!GameDreamFactory\chars\道具\百兵\百兵.def"

details:
"!GameDreamFactory\游戏梦工厂&Mugen的教程\游戏梦工厂\Sctrls(人物的State)\StageAddPlayer(场景添加人物).txt"

**Comment by qingjun1991** [comment]
The usage of SelectAddPlayer is similar to StageAddPlayer.

This is an example of unlock characters and stages:
"!GameDreamFactory\data\system.def"
"!GameDreamFactory\chars\道具\TitleScreen"

details:
"!GameDreamFactory\游戏梦工厂&Mugen的教程\游戏梦工厂\Sctrls(人物的State)\SelectAddPlayer(选人添加人物).txt"
