### ISSUE TITLE
what is 命令行启动.bat?

### ISSUE THREAD

**Issue by CheeksTheOriginal** [qingjun1991/GameDreamFactory#30]

**Comment by qingjun1991** [comment]
This is like the command line of Mugen.

**Comment by CheeksTheOriginal** [comment]
> This is like the command line of Mugen.

how do i get it to run?

**Comment by qingjun1991** [comment]
Double click to run on the Windows operating system.

You can also use other shortcut functions, such as the Training button on the main window and "!GameDreamFactory\游戏梦工厂&Mugen的教程\游戏梦工厂\Sctrls(人物的State)\MatchReStart(重开此局).txt".
