### ISSUE TITLE
How to i trigger the ChangeTouchButtonDef only once

### ISSUE THREAD

**Issue by CheeksTheOriginal** [qingjun1991/GameDreamFactory#31]
how do i get this to trigger the moment i enter training mode without making it permanent 

[State ] ;training touch controls p1
type = ChangeTouchButtonDef
trigger1 = GameMode = "Training" && command = "hold＜RLeft_sys" && var(59) = 0
def = misc/layouts/training-p1-layout.def

**Comment by qingjun1991** [comment]
There are many methods, such as:
"!GameDreamFactory\游戏梦工厂&Mugen的教程\游戏梦工厂\Trigger(人物的Trigger)\RoundTime(获取当局到现在经过的帧数).txt"
"!GameDreamFactory\游戏梦工厂&Mugen的教程\游戏梦工厂\Trigger(人物的Trigger)\ExistTime(实体的存在时长).txt"
"!GameDreamFactory\游戏梦工厂&Mugen的教程\游戏梦工厂\Trigger(人物的Trigger)\UpdateTime(实体的运转时长).txt"
