### ISSUE TITLE
Can we get a character limiter to stop infinite amounts of selection when packaging the game

### ISSUE THREAD

**Issue by CheeksTheOriginal** [qingjun1991/GameDreamFactory#34]

**Comment by qingjun1991** [comment]
Modify the .cfg file:
SelectPlayerCountMax=1

**Comment by CheeksTheOriginal** [comment]
> Modify the .cfg file: SelectPlayerCountMax=1

only arcade huh. 😅

**Comment by qingjun1991** [comment]
Yes, because I need unlimited and I don't want players to frequently modify ,cfg file.

**Comment by CheeksTheOriginal** [comment]
> Yes, because I need unlimited and I don't want players to frequently modify ,cfg file.

can't -1 be unlimited then for players who want that

**Comment by qingjun1991** [comment]
Yes, because the default value is 2147483647, which is also the maximum value, and this value is so large that it is considered unlimited.

**Comment by CheeksTheOriginal** [comment]
> Yes, because the default value is 2147483647, which is also the maximum value, and this value is so large that it is considered unlimited.

so can you set -1 as unlimited and other numbers as limited because i don't want them to select alot of players and win easily

**Comment by qingjun1991** [comment]
I think the result is the same whether or not to add -1, but after adding -1, it is necessary to explain the meaning of -1 in the .cfg file, which makes the .cfg file a bit more complicated, so I don't want to add it.

**Comment by CheeksTheOriginal** [comment]
> I think the result is the same whether or not to add -1, but after adding -1, it is necessary to explain the meaning of -1 in the .cfg file, which makes the .cfg file a bit more complicated, so I don't want to add it.

i was talking about non arcade

**Comment by qingjun1991** [comment]
Non arcade is just simple game, there is no need for limited.

Reason 1: Custom gameplay is a major highlight of this engine. If limited, the Tag Mode, Turns Mode, Scuffle Mode... will become ineffective.

Reason 2: If a player chooses 10 vs 1, there is no need to stop him. They're just curious, and they know it's unfair. They won't show off how powerful they are.

Reason 3: If you are playing with friends, all you need to do is explain to them that can only choose one character, and they will definitely agree, unless you are playing games for the sake of arguing.
