### ISSUE TITLE
Chars able to die on training mode

### ISSUE THREAD

**Issue by NuggetFangus** [qingjun1991/GameDreamFactory#36]
their health should go up again, and be unable to die

**Comment by qingjun1991** [comment]
This is for flexible control and testing, such as residual blood skills, victory animations, death animations....

You can uncomment at the end of the code "!GameDreamFactory\SystemAI.cns" to meet your needs:

;;让训练模式，常时满血满气满时间
;[State ]
;type = LifeSet
;trigger1 = !IsHelper && GameMode = "Training"
;value = LifeMax
;
;[State ]
;type = PowerSet
;trigger1 = !IsHelper && GameMode = "Training"
;value = PowerMax
;
;[State ]
;type = RoundClockTimeSet
;trigger1 = !IsHelper && GameMode = "Training"
;value = -1

**Comment by NuggetFangus** [comment]
Oh ok
