### ISSUE TITLE
NotExistedCharHasSpace  = 0 doesn't seem to work

### ISSUE THREAD

**Issue by CheeksTheOriginal** [qingjun1991/GameDreamFactory#37]

**Comment by qingjun1991** [comment]
You may have misunderstood its function. Why did you set this up?

**Comment by CheeksTheOriginal** [comment]
> You may have misunderstood its function. Why did you set this up?

what does it do?

**Comment by qingjun1991** [comment]
This is to set the text display way, generally do not have to set it.

**Comment by CheeksTheOriginal** [comment]
> This is to set the text display way, generally do not have to set it.

how to edit .dll Files

**Comment by qingjun1991** [comment]
Cannot edit.
