### ISSUE TITLE
can the game use internal storage as memory like a .swp file so it crashes from memory overload less 

### ISSUE THREAD

**Issue by CheeksTheOriginal** [qingjun1991/GameDreamFactory#39]

**Comment by qingjun1991** [comment]
Yes, modify .cfg file:
PlayerCache=0
UseImageCache=1

But if the game is too large, it still need requires a large amount of running memory, resulting in little effect.

**Comment by CheeksTheOriginal** [comment]
what is lu master apk?

**Comment by qingjun1991** [comment]
Some mobile phone manufacturers will relax restrictions on the Lu Master Edition.

**Comment by CheeksTheOriginal** [comment]
> Some mobile phone manufacturers will relax restrictions on the Lu Master Edition.

where to get it

**Comment by qingjun1991** [comment]
Already uploaded!
