### ISSUE TITLE
what cqj.libs folder files are necessary for android?

### ISSUE THREAD

**Issue by CheeksTheOriginal** [qingjun1991/GameDreamFactory#41]

**Comment by qingjun1991** [comment]
Why study this? Basically all of them will be used, and those that are not currently used will gradually be used later, so don't waste time researching this, it's meaningless.

**Comment by CheeksTheOriginal** [comment]
> Why study this? Basically all of them will be used, and those that are not currently used will gradually be used later, so don't waste time researching this, it's meaningless.

ok
