### ISSUE TITLE
Game Dream Factory crashing

### ISSUE THREAD

**Issue by NuggetFangus** [qingjun1991/GameDreamFactory#44]
I tried adding another mugen game into game dream factory, but it just crashes, i deleted it and now it keeps crashing

**Comment by NuggetFangus** [comment]
It crashes when i try to boot mugen

**Comment by qingjun1991** [comment]
Some important files in this folder "/!GameDreamFactory" have been deleted, download again can solve the problem.

**Comment by NuggetFangus** [comment]
I did and it fixed the issue, but i dont think i had deleted important files in the folder

**Comment by NuggetFangus** [comment]
Also, will there be add004 support in game dream factory?

**Comment by qingjun1991** [comment]
> I did and it fixed the issue, but i dont think i had deleted important files in the folder

You can compare two folders to see what files are missing and think about why these files are missing.

**Comment by qingjun1991** [comment]
> Also, will there be add004 support in game dream factory?

https://github.com/qingjun1991/GameDreamFactory/issues/22#issuecomment-2210377563

**Comment by NuggetFangus** [comment]
Oh, i already asked that
