### ISSUE TITLE
ikemen Go 

### ISSUE THREAD

**Issue by Rafaelfilp** [qingjun1991/GameDreamFactory#5]
Good afternoon, when will ikemen Go be supported in dreamfactory?

**Comment by qingjun1991** [comment]
Ikemen-GO是一个很强大的引擎，我也很喜欢它，你可以使用exagear在安卓手机玩到它，https://www.bilibili.com/video/BV1iV4y197RU

游戏梦工厂，不是一个Windows模拟器，所以不支持Ikemen-GO

Ikemen-GO比mugen多了非常多的功能，而且它一直在更新，所以想要兼容它也是很难的

游戏梦工厂，也是比mugen多了非常多的功能，本身就已经很复杂了，所以暂时不考虑去兼容Ikemen-GO

**Comment by Rafaelfilp** [comment]
Will there be a 3 vs 3 mode?

**Comment by qingjun1991** [comment]
已经实现了的，在选择人物前，不是需要选择人数吗，可以 无限 vs 无限
如果你喜欢车轮战，"!GameDreamFactory\stages\kfm宽屏车轮战.def"，选择这个场景，就能玩到车轮战；你也可以参考这个场景制作车轮战场景

**Comment by Rafaelfilp** [comment]
Will there be optimization in dreamfactory? I played a mugen and it was crashing a lot

**Comment by qingjun1991** [comment]
I have good news to tell all enthusiasts that Android phones can now run the latest versions of IKEMEN GO engine and MUGEN engine smoothly, The following is a video tutorial.
https://www.bilibili.com/video/BV1SfjQzQEnx
