### ISSUE TITLE
Controller issue

### ISSUE THREAD

**Issue by NuggetFangus** [qingjun1991/GameDreamFactory#7]
How can i add taunt controller support? All buttons work but select and dpad doesnt

**Comment by qingjun1991** [comment]
Are you connected to the joystick,As a result,the taunt button and direction button were pressed without any response？

If that's the case, you need to try modify other value in the [P1 Joystick] in the . cfg file

**Comment by NuggetFangus** [comment]
I tried, but i dont know why it doesnt work properly, the other buttons seem fine besides those two

**Comment by qingjun1991** [comment]
Are you using an Android phone with a joystick？
If that's the case, you try this:
"!GameDreamFactory\游戏梦工厂&Mugen的教程\游戏梦工厂\1、说明、问题、教程\4.10、安卓版如何使用USB游戏手柄.txt"
"!GameDreamFactory\游戏梦工厂&Mugen的教程\游戏梦工厂\1、说明、问题、教程\USB蓝牙手柄控制中心_USB BT Joystick Center Gold.apk"

**Comment by NuggetFangus** [comment]
My joystick is bluetooth, but i tested my usb keyboard and it worked just fine

**Comment by qingjun1991** [comment]
The solution mentioned above should be able to solve the problem

**Comment by NuggetFangus** [comment]
Didnt work, but maybe its my controller's problem, or maybe i didnt put the correct button number
