### ISSUE TITLE
Crashing

### ISSUE THREAD

**Issue by NuggetFangus** [qingjun1991/GameDreamFactory#8]
Sometimes the app crash when launching or when i enter in the mugen, is there any way i can fix it?

**Comment by qingjun1991** [comment]
This is an issue with the mobile operating system. Some mobile operating systems limit the memory occupied by the app, and if it exceeds 0.5g, the app will be kill, causing a crash

Mobile phone brands that may have this issue: vivo, Oppo, OnePlus...
Mobile phone brands that should not have this issue: Xiaomi、Redmi、HUAWEI...

The simple solution is to remove some characters to solve the problem

details: "!GameDreamFactory\游戏梦工厂&Mugen的教程\游戏梦工厂\1、说明、问题、教程\4.3、安卓版黑屏闪退问题.txt"

**Comment by qingjun1991** [comment]
This is an issue with the mobile operating system. Some mobile operating systems limit the memory occupied by the app, and if it exceeds 0.5g, the app will be kill, causing a crash

Mobile phone brands that may have this issue: vivo, Oppo, OnePlus...
Mobile phone brands that should not have this issue: Xiaomi, Redmi, HUAWEI...

a simple solution is to remove some characters to solve the problem

details: "!GameDreamFactory\游戏梦工厂&Mugen的教程\游戏梦工厂\1、说明、问题、教程\4.3、安卓版黑屏闪退问题.txt"

**Comment by NuggetFangus** [comment]
Mine is a xiaomi redmi so i dont know why i have this issue, but i will try to remove some characters to try to solve it

**Comment by YanisCr777** [comment]
how did you fix the issue

> Mine is a xiaomi redmi so i dont know why i have this issue, but i will try to remove some characters to try to solve it

**Comment by NuggetFangus** [comment]
After the update i didnt have the issue anymore

**Comment by YanisCr777** [comment]
But How ?
Are you using heavy characters and a heavy screenpack too ?
My Game dream factory folder is arround 4gb now, can you tell me your
phone's name please 🙏 because I have only 4gb ram only

Le sam. 11 mai 2024 à 17:31, NuggetFangus ***@***.***> a
écrit :

**Comment by NuggetFangus** [comment]
Sorry for taking so long to answer, i didnt see your message, and no, i dont have much heavy characters and a heavy screenpack, because it takes a lot of time to load and sometimes it crashes, so no jus characters for now i guess

**Comment by NuggetFangus** [comment]
My phone is a xiaomi note 12s

**Comment by NuggetFangus** [comment]
Yeah now cant even open the modes in mugen, it crashes, i already deleted the chara that were making it crash, but still crashes

**Comment by qingjun1991** [comment]
> Yeah now cant even open the modes in mugen, it crashes, i already deleted the chara that were making it crash, but still crashes
Make sure you have updated the latest patch, including latest APK.
If it still crashes, Take a look at the content of "!GameDreamFactory/log.txt".

**Comment by qingjun1991** [comment]
> Yeah now cant even open the modes in mugen, it crashes, i already deleted the chara that were making it crash, but still crashes

Make sure you have updated the latest patch, including latest APK.
If it still crashes, Take a look at the content of "!GameDreamFactory/log.txt".

**Comment by NuggetFangus** [comment]
I found this in the log.txt

文件不存在：font/arial.ttf


动画1不存在,data/yuki/../yuki/PS1_Startup.def


文件不存在：stages/SMB3_Title_Screen.def


文件不存在：stages/stage0-720.def

**Comment by qingjun1991** [comment]
That should be simply a crash caused by occupying too much running memory.

**Comment by qingjun1991** [comment]
Please send me the download link for the game for research.

**Comment by NuggetFangus** [comment]
Mine is a custom one, i dont have a link

**Comment by qingjun1991** [comment]
You can investigate it yourself.
First ensure that the apk is the latest version. Then only retain one character and one stage. 
This should be able to play normally. If it still crashes,  it indicates that your screen package file is very large, causing it to occupy a lot of running memory.

**Comment by NuggetFangus** [comment]
I think its a bug, cause my screenpack is not heavy, but i do have a lot of chars, but they were working before

**Comment by NuggetFangus** [comment]
It just happened because i downloaded 6 heavy chars, but dven after removing them still crashes

**Comment by qingjun1991** [comment]
Are you only removing characters from the "select.def" file? You must remove the character files in the "chars" folder.

**Comment by NuggetFangus** [comment]
I did it but still crashes, it just stops crashing when i have only 1 character, but it was working before with all my characters

**Comment by NuggetFangus** [comment]
Maybe the chars were stored in some part of mugen and now they are using memory making it crash

**Comment by qingjun1991** [comment]
Give it a try, uninstall APK first, and then install APK again.

**Comment by NuggetFangus** [comment]
Already did it, it didnt work

**Comment by qingjun1991** [comment]
Give it a try, open the .cfg file, add or modify:
[Config]
UpdateUseNewThread=0

**Comment by NuggetFangus** [comment]
It didnt work

**Comment by NuggetFangus** [comment]
I'll be waiting for the next update to see if its fixed, but thanks for helping me!

**Comment by NuggetFangus** [comment]
Maybe you could try to add higher ram usage priority on the app

**Comment by qingjun1991** [comment]
> Maybe you could try to add higher ram usage priority on the app

This is controlled by the Android system, app cannot control it.

**Comment by NuggetFangus** [comment]
Oh i didnt knew that

**Comment by qingjun1991** [comment]
> I did it but still crashes, it just stops crashing when i have only 1 character, but it was working before with all my characters

This indicates that there is a very large character pack in your "chars" folder, which occupies too much running memory and is why it crashes. Try to find and remove it.

**Comment by qingjun1991** [comment]
Do you use an SD card? Due to the limitations of the new version of Android system, the application can not directly read the SD card files, need to use a special way to read the file, it read the file is very slow, and will take up a lot of running memory.

**Comment by NuggetFangus** [comment]
It only stops crashing when i delete a lot of characters, and i dont use the mugen on sd card

**Comment by qingjun1991** [comment]
Maybe it's related to the settings, please send me ,cfg file to take a look.

**Comment by NuggetFangus** [comment]
[mugen.cfg.zip](https://github.com/user-attachments/files/16046321/mugen.cfg.zip)

**Comment by NuggetFangus** [comment]
I think its because of the characters that i tried to add, i tried to add 6 heavy characters all at once, and after that it started crashing, even after removing them

**Comment by NuggetFangus** [comment]
I THINK I FOUND THE ISSUE

**Comment by NuggetFangus** [comment]
I had a character that was with a stage that did not exist, so after i added the correct stage, it stopped crashing

**Comment by qingjun1991** [comment]
It shouldn't be. It is allowed that the stage does not exist. Unless none of the stage in the "select.def" file exist.

**Comment by NuggetFangus** [comment]
I know, but it did fix the issue

**Comment by qingjun1991** [comment]
> I had a character that was with a stage that did not exist, so after i added the correct stage, it stopped crashing

How the character is written in "select.def" file?

**Comment by NuggetFangus** [comment]
D_Miku, stages/MIKU_CITY.def

Was previously another stage, that i had removed, but it was with her in the select.def

**Comment by qingjun1991** [comment]
Maybe there was something wrong with the previous one. Please send me the previous “select.def” file to take a look.

**Comment by NuggetFangus** [comment]
[select(Copy).def.zip](https://github.com/user-attachments/files/16046411/select.Copy.def.zip)

**Comment by qingjun1991** [comment]
I tried to add it:
Athena_type-M, stages/MIKU_LOUNGE.def
Athena_type-M, stages/MIKU_CITY.def
D_Miku, stages/MIKU_LOUNGE.def
D_Miku, stages/MIKU_CITY.def

stage don't exist. Can still play normally. Maybe there's something special about your game.

**Comment by NuggetFangus** [comment]
I dont know why it happens, but it did

**Comment by qingjun1991** [comment]
If you want to know the root cause, you need to send me your game, remove irrelevant characters and stages. As long as your problem can be reproduced on my phone, I can quickly find the root cause.

If you don't need to know the root cause, then ignore it.
