### ISSUE TITLE
More controller support suggestion

### ISSUE THREAD

**Issue by NuggetFangus** [qingjun1991/GameDreamFactory#9]
Can you add an controller mapper in the launcher? Like before you enter mugen

**Comment by qingjun1991** [comment]
Do you mean state controller or joystick controller？

**Comment by NuggetFangus** [comment]
Joystick

**Comment by qingjun1991** [comment]
I don't plan to do this feature at the moment. The main reason is that options is not very useful.
There are too many settings options, It is more convenient to change .cfg file directly

For example, when downloaded Mugen works, simply copy the [P1 Joystick] from "!GameDreamFactory\data\Main.cfg" to replace the [P1 Joystick] from "Mugen works\data\mugen.cfg", which is very convenient, without need to go to options to set the button mapping
